version: '3'

networks:
    3lips:

services:

  3lips:
    restart: always
    build: .
    image: 3lips
    ports:
      - 49156:5000
    networks:
      - 3lips
    container_name: 3lips

  cesium-apache:
    restart: always
    build:
      context: ./cesium
      dockerfile: Dockerfile
    image: cesium-apache
    networks:
      - 3lips
    container_name: 3lips-cesium

