version: '3'

networks:
    3lips:

services:

  api:
    restart: always
    build:
      context: .
      dockerfile: ./api/Dockerfile
    image: 3lips-api
    ports:
      - 49156:5000
    networks:
      - 3lips
    volumes:
      - ./common:/app/common
    container_name: 3lips-api

  event:
    restart: always
    build:
      context: ./event
      dockerfile: Dockerfile
    image: 3lips-event
    networks:
      - 3lips
    volumes:
      - ./common:/app/common
    container_name: 3lips-event

  cesium-apache:
    restart: always
    build:
      context: ./cesium
      dockerfile: Dockerfile
    image: cesium-apache
    networks:
      - 3lips
    container_name: 3lips-cesium